services:
  redis:
    image: redis:7
    ports: ["6379:6379"]

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    command: server /data --console-address ":9001"
    ports: ["9000:9000", "9001:9001"]
    volumes: ["minio-data:/data"]

  api:
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
    env_file: ../.env
    ports: ["8000:8000"]
    depends_on: [redis, minio]

  worker:
    build:
      context: ..
      dockerfile: docker/worker.Dockerfile
    env_file: ../.env
    depends_on: [redis, minio, api]

  ui:
    build:
      context: ..
      dockerfile: docker/ui.Dockerfile
    env_file: ../.env
    ports: ["7860:7860"]
    depends_on: [api]

volumes:
  minio-data:
